config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tickets
  resources :comments, only: [:create, :destroy]
  get 'unassigned_tickets' => 'unassigned_tickets#index'
  get 'open_tickets' => 'open_tickets#index'
  get 'on_hold_tickets' => 'on_hold_tickets#index'
  get 'closed_tickets' => 'closed_tickets#index'
  get 'search' => 'search#index'

  root 'tickets#new'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :ticket

  validates :ticket, presence: true
  validates :body, presence: true
  validates :name, presence: true
  validates :email, presence: true

  after_create :send_email_on_comment_create

  private

  def send_email_on_comment_create
    CreateCommentMailer.email_for(self).deliver_later
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :tickets

  validates :name, presence: true
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :tickets

  validates :name, presence: true
end

app/models/ticket.rb
require 'uid_generator'

class Ticket < ActiveRecord::Base
  belongs_to :status
  has_many :comments, dependent: :destroy
  belongs_to :department
  belongs_to :user

  validates :name, presence: true
  validates :email, presence: true
  validates :summary, presence: true
  validates :body, presence: true
  validates :department, presence: true

  before_create :generate_uid, :set_status
  after_create :send_email_on_ticket_create

  update_index 'tickets#ticket', :self

  def to_param
    uid
  end

  def first_name
    name.split.first
  end

  def self.unassigned_tickets
    where(user_id: nil)
  end

  def self.open_tickets
    exclude_ids = []
    exclude_ids << Status.find_by_name('Cancelled').id
    exclude_ids << Status.find_by_name('Completed').id
    ids = Status.all.map(&:id) - exclude_ids
    where(status_id: ids)
  end

  def self.on_hold_tickets
    Status.find_by_name('On Hold').tickets
  end

  def self.closed_tickets
    ids = []
    ids << Status.find_by_name('Cancelled').id
    ids << Status.find_by_name('Completed').id
    where(status_id: ids)
  end

  private

  def generate_uid
    self.uid ||= UidGenerator.new.generate
  end

  def set_status
    self.status_id ||= Status.find_by_name!('Waiting for Staff Response').id
  end

  def send_email_on_ticket_create
    CreateTicketMailer.email_for(self).deliver_later
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/closed_tickets_controller.rb
class ClosedTicketsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tickets = Ticket.closed_tickets
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # POST /comments
  def create
    @comment = Comment.new(comment_params)
    service = SendEmailOnTicketUpdateService.new(
      @comment.ticket, ticket_params, UpdateTicketMailer, current_user)

    if @comment.save && service.execute
      redirect_to @comment.ticket, notice: 'Comment was successfully created.'
    else
      redirect_to @comment.ticket, alert: 'Can not create comment.'
    end
  end

  # DELETE /comments/1
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.ticket, notice: 'Comment was successfully destroyed.'
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:name, :email, :body, :ticket_id)
  end

  def ticket_params
    if current_user
      params.require(:ticket).permit(:status_id, :user_id)
    else
      params.require(:ticket).permit(:status_id)
    end
  end
end

app/controllers/on_hold_tickets_controller.rb
class OnHoldTicketsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tickets = Ticket.on_hold_tickets
  end
end

app/controllers/open_tickets_controller.rb
class OpenTicketsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tickets = Ticket.open_tickets
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:q]
      @tickets = TicketsSearch.new(params[:q]).search.load
    else
      @tickets = []
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  def show
    @comments = @ticket.comments.all
    @comment = @ticket.comments.build
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to @ticket, notice: 'Ticket was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tickets/1
  def update
    result = SendEmailOnTicketUpdateService.new(
      @ticket, ticket_params, UpdateTicketMailer, current_user).execute
    if result
      redirect_to @ticket, notice: 'Ticket was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tickets/1
  def destroy
    @ticket.destroy
    redirect_to tickets_url, notice: 'Ticket was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find_by_uid(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    if current_user
      params.require(:ticket).permit(:name, :email, :summary, :body, :department_id, :status_id, :user_id)
    else
      params.require(:ticket).permit(:name, :email, :summary, :body, :department_id, :status_id)
    end
  end
end

app/controllers/unassigned_tickets_controller.rb
class UnassignedTicketsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tickets = Ticket.unassigned_tickets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/closed_tickets_helper.rb
module ClosedTicketsHelper
end

app/helpers/on_hold_tickets_helper.rb
module OnHoldTicketsHelper
end

app/helpers/open_tickets_helper.rb
module OpenTicketsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/unassigned_tickets_helper.rb
module UnassignedTicketsHelper
end

app/views/closed_tickets/index.html.haml
%h1 Closed tickets

- if @tickets.any?
  %table.table.table-hover.table-bordered
    %thead
      %tr
        %th
          %b UID:
        %th
          %b
            Status:
        %th
          %b Summary:
    - @tickets.each do |ticket|
      %tr
        %td= link_to ticket.uid, ticket_path(ticket)
        %td= link_to ticket.status.name, ticket_path(ticket)
        %td= link_to ticket.summary, ticket_path(ticket)

app/views/comments/_form.html.haml
= form_for(@comment, html: { role: 'form' }) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{ pluralize(@comment.errors.count, 'error') } prohibited this comment from being saved:"
      %ul
      - @comment.errors.full_messages.each do |message|
        %li= message

  = f.hidden_field :ticket_id
  .form-group
    = f.label :name
    .input-group
      .input-group-addon= icon('user')
      = f.text_field :name, class: 'form-control', required: 'required', placeholder: 'e.g. John Snow or Barbra Streisand'
  .form-group
    = f.label :email
    .input-group
      .input-group-addon= icon('envelope')
      - if current_user
        = f.email_field :email, class: 'form-control', required: 'required', placeholder: 'me@example.com', value: "#{ current_user.email }"
      - else
        = f.email_field :email, class: 'form-control', required: 'required', placeholder: 'me@example.com'
  - if current_user
    .form-group
      = label :ticket, :user_id, 'Assigned to:'
      .input-group
        = select :ticket, :user_id, User.all.collect { |u| [u.email, u.id] }, { include_blank: true }, { class: 'selectpicker' }
  .form-group
    = label :ticket, :status_id, 'Status:'
    .input-group
      = select :ticket, :status_id, Status.all.collect { |s| [s.name, s.id] }, { include_blank: false }, { class: 'selectpicker' }
  .form-group
    = f.label :body, 'Comment'
    = f.text_area :body, class: 'form-control', rows: 8, required: 'required', placeholder: 'Comment body'
  %button{ type: 'submit', class: 'btn btn-primary' }
    = icon('paper-plane')
    &nbsp;Send

app/views/layouts/application.html.haml
!!!
%html
  %head>
    %title Support Issue Tracker
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    .container
      - if alert
        .alert.alert-warning.alert-dismissible{ role: 'alert'}
          %button.close{ :type => 'button', :'data-dismiss' => 'alert', :'aria-label' => 'Close' }
            %span{ :'aria-hidden' => 'true' }
              &times;
          = alert

      - if notice
        .alert.alert-success.alert-dismissible{ role: 'alert'}
          %button.close{ :type => 'button', :'data-dismiss' => 'alert', :'aria-label' => 'Close' }
            %span{ :'aria-hidden' => 'true' }
              &times;
          = notice

      = link_to 'New ticket', new_ticket_path, class: 'btn btn-primary'
      \|
      - if user_signed_in?
        = link_to 'Unassigned tickets', unassigned_tickets_path, class: 'btn btn-primary'
        = link_to 'Open tickets', open_tickets_path, class: 'btn btn-primary'
        = link_to 'On hold tickets', on_hold_tickets_path, class: 'btn btn-primary'
        = link_to 'Closed tickets', closed_tickets_path, class: 'btn btn-primary'
        = link_to 'Search', search_path, class: 'btn btn-primary'
        \|
        = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-primary'
      - else
        = link_to 'Sign in', new_user_session_path, class: 'btn btn-primary'
        \|
        = link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary'

      = yield

app/views/on_hold_tickets/index.html.haml
%h1 On Hold tickets

- if @tickets.any?
  %table.table.table-hover.table-bordered
    %thead
      %tr
        %th
          %b UID:
        %th
          %b
            Status:
        %th
          %b Summary:
    - @tickets.each do |ticket|
      %tr
        %td= link_to ticket.uid, ticket_path(ticket)
        %td= link_to ticket.status.name, ticket_path(ticket)
        %td= link_to ticket.summary, ticket_path(ticket)

app/views/open_tickets/index.html.haml
%h1 Open tickets

- if @tickets.any?
  %table.table.table-hover.table-bordered
    %thead
      %tr
        %th
          %b UID:
        %th
          %b
            Status:
        %th
          %b Summary:
    - @tickets.each do |ticket|
      %tr
        %td= link_to ticket.uid, ticket_path(ticket)
        %td= link_to ticket.status.name, ticket_path(ticket)
        %td= link_to ticket.summary, ticket_path(ticket)

app/views/search/index.html.haml
%h1 Search:

= form_tag search_path, method: :get, class: 'form-inline' do
  .form-group
    .input-group
      .input-group-addon= icon('search')
      = text_field_tag :q, params[:q] ? params[:q] : '', placeholder: 'Search...', size: '50', class: 'form-control'
  %button{ type: 'submit', class: 'btn btn-primary' } Find

- if @tickets.any?
  %br

  %table.table.table-hover.table-bordered
    %thead
      %tr
        %th
          %b UID:
        %th
          %b
            Status:
        %th
          %b Summary:
    - @tickets.each do |ticket|
      %tr
        %td= link_to ticket.uid, ticket_path(ticket)
        %td= link_to ticket.status.name, ticket_path(ticket)
        %td= link_to ticket.summary, ticket_path(ticket)

app/views/tickets/_form.html.haml
= form_for(@ticket, html: { role: 'form' }) do |f|
  - if @ticket.errors.any?
    #error_explanation
      %h2= "#{ pluralize(@ticket.errors.count, 'error') } prohibited this ticket from being saved:"
      %ul
        - @ticket.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    .input-group
      .input-group-addon= icon('user')
      = f.text_field :name, class: 'form-control', required: 'required', placeholder: 'e.g. John Snow or Barbra Streisand', autofocus: 'autofocus'
  .form-group
    = f.label :email
    .input-group
      .input-group-addon= icon('envelope')
      = f.email_field :email, class: 'form-control', required: 'required', placeholder: 'me@example.com'
  .form-group
    = f.label :department
    .input-group
      = f.collection_select :department_id, Department.all, :id, :name, { include_blank: false }, { class: 'selectpicker' }
  - unless @ticket.new_record?
    .form-group
      = f.label :status
      .input-group
        = f.collection_select :status_id, Status.all, :id, :name, { include_blank: false }, { class: 'selectpicker' }
  - if current_user && !@ticket.new_record?
    .form-group
      = f.label :user_id, 'Assigned to:'
      .input-group
        = f.collection_select :user_id, User.all, :id, :email, { include_blank: true }, { class: 'selectpicker' }
  .form-group
    = f.label :summary
    = f.text_field :summary, class: 'form-control', required: 'required', placeholder: 'Short ticket summary'
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control', rows: 8, required: 'required', placeholder: 'Full ticket description'
  %button{ type: 'submit', class: 'btn btn-primary' }
    = icon('paper-plane')
    &nbsp;Send
  - unless @ticket.new_record?
    \|
    = link_to 'Show ticket', @ticket, class: 'btn btn-primary'

app/views/tickets/edit.html.haml
%h1 Editing ticket

.highlight
  = render 'form'

app/views/tickets/index.html.haml
%h1 Listing tickets

%table
  %thead
    %tr
      %th Email
      %th Summary
      %th Body
      %th Uid
      %th
      %th
      %th

  %tbody
    - @tickets.each do |ticket|
      %tr
        %td= ticket.email
        %td= ticket.summary
        %td= ticket.body
        %td= ticket.uid
        %td= link_to 'Show', ticket
        %td= link_to 'Edit', edit_ticket_path(ticket)
        %td= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Ticket', new_ticket_path

= icon('flag')

app/views/tickets/new.html.haml
%h1 New ticket

.highlight
  = render 'form'

app/views/tickets/show.html.haml
%div
  %h3
    %b Summary:
    = "[#{ @ticket.uid }] #{ @ticket.summary }"

.highlight
  %div
    %b Created by:
    = "#{ @ticket.name } (#{ @ticket.email }) #{ time_ago_in_words(@ticket.created_at) } ago"

  %div
    %b Status:
    = @ticket.status.name

  %div
    %b Department:
    = @ticket.department.name

  - if @ticket.user
    %div
      %b Assigned to:
      = @ticket.user.email

  %div
    %b Description:
    = simple_format @ticket.body

  = link_to 'Edit', edit_ticket_path(@ticket), class: 'btn btn-primary'
  \|
  = link_to 'Destroy', @ticket, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'


- if @comments.any?
  %h3 Comments:
  - @comments.each do |comment|
    .highlight
      %strong= "#{ comment.name } (#{ comment.email }) #{ time_ago_in_words(comment.created_at) } ago"
      %br
      %p= simple_format comment.body
      %p= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary'

.highlight
  = render 'comments/form'

app/views/unassigned_tickets/index.html.haml
%h1 Unassigned tickets

- if @tickets.any?
  %table.table.table-hover.table-bordered
    %thead
      %tr
        %th
          %b UID:
        %th
          %b
            Status:
        %th
          %b Summary:
    - @tickets.each do |ticket|
      %tr
        %td= link_to ticket.uid, ticket_path(ticket)
        %td= link_to ticket.status.name, ticket_path(ticket)
        %td= link_to ticket.summary, ticket_path(ticket)